#server:
#  port: 8088
#spring:
#  application:
#    name: service-product
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.151/shop? serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: 123456
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  cloud:
#    nacos:
#      discovery:
#        server-addr: server.liuhongchen.com:28848
#logging:
#  level:
#    root: info
#    org.springframework.cloud.sleuth: DEBUG
##    org.springframework.web.servlet.DispatcherServlet: DEBUG
